name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      # - name: Install dependencies
      #   run: npm i @rollup/rollup-linux-x64-gnu && npm ci

      # - name: Build project
      #   run: npx vite build

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/skfe:prod .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/skfe:prod

      - name: Deploy to VPS
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ${{ secrets.SSH_HOST }} << 'EOF'
          echo "ðŸ” Finding container using port 80..."
          CONTAINER_ID=$(docker ps --filter "publish=80" --format '{{.ID}}')
          if [ -n "$CONTAINER_ID" ]; then
            echo "ðŸ›‘ Stopping container $CONTAINER_ID"
            docker stop $CONTAINER_ID
            docker rm $CONTAINER_ID
          else
            echo "âœ… No container using port 80"
          fi

          echo "ðŸ“¦ Pulling latest image..."
          docker pull ${{ secrets.DOCKER_USERNAME }}/skfe:prod

          echo "ðŸš€ Running new container..."
          docker run -d --name skfe -p 80:80 ${{ secrets.DOCKER_USERNAME }}/skfe:prod
          EOF
